# Sentence Analyzer
text = input("Enter a sentence: ")
words = text.split()
chars = len(text)
chars_no_space = len(text.replace(" ", ""))
vowels = sum(1 for c in text.lower() if c in "aeiou")
consonants = sum(1 for c in text.lower() if c.isalpha() and c not in "aeiou")
print(f"\nWords: {len(words)}")
print(f"Characters: {chars}")
print(f"Characters (no spaces): {chars_no_space}")
print(f"Vowels: {vowels}")
print(f"Consonants: {consonants}")
print(f"Longest word: {max(words, key=len)}")
print(f"Shortest word: {min(words, key=len)}")
