h = float(input("Height (m): "))
w = float(input("Weight (kg): "))
bmi = w / (h**2)
print(f"BMI: {bmi:.2f}")
if bmi < 18.5: print("Underweight")
elif bmi < 25: print("Normal")
else: print("Overweight")